### ISSUE TITLE
Internal UI for YAML builder + Deployment

### ISSUE THREAD

**Issue by satyajit1401** [Aroha-Labs/mira-sdk-python#59]
### Test cases 
- [ ] UI to add input parameters, set their names, descriptions and type
- [ ] UI to select model 
- [ ] UI to write system prompt and reference the variables in it
- [ ] UI to add required input parameters and test the flow with a single click
- [ ] UI to deploy the flow after adding - name, flow description, flow version 
- [ ] Functionality to test the flow in real-time through the UI
- [ ] Functionality to deploy the flow with the input parameters, system prompt, model, and all the descriptions and formats through the UI

**Comment by rachit1994** [comment]
PR: https://github.com/Aroha-Labs/console-ui/pull/10
